#!/usr/bin/env bash

if [[ "$(git stash -u)" != "No local changes to save" ]]; then
  STASHED=1
fi

branch_name=$(git rev-parse --abbrev-ref HEAD)
main_branch_name=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
git checkout $main_branch_name
git branch -d $branch_name
git pull origin $main_branch_name

[ "$STASHED" == "1" ] && git stash pop
