#!/usr/bin/env bash

if [[ "$(git stash -u)" != "No local changes to save" ]]; then
  STASHED=1
fi

git pull origin $(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@') "$@"

[ "$STASHED" == "1" ] && git stash pop
